{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "from bokeh.io import show, output_notebook,output_file, show, save, curdoc, output_notebook, export_png\n",
    "from bokeh.plotting import figure, output_file, show,save\n",
    "from bokeh.models.widgets import Panel, Tabs\n",
    "from bokeh.layouts import column, row, widgetbox\n",
    "from bokeh.models import  HoverTool, LinearColorMapper,TextInput,Label,LabelSet,Title,CustomJS,\\\n",
    "        Slider, Div,RangeSlider, Button,RadioGroup,LinearAxis, Range1d, ColumnDataSource, Paragraph,Select\n",
    "\n",
    "from bokeh.tile_providers import CARTODBPOSITRON, get_provider,OSM, STAMEN_TERRAIN\n",
    "\n",
    "#Load data\n",
    "mid_dyn = pd.read_csv(\"data/MiddleSchools_2006-2018_clean.csv\")\n",
    "high_dyn = pd.read_csv(\"data/HighSchools_2006-2018_clean.csv\")\n",
    "\n",
    "mid_stat = pd.read_csv(\"data/MiddleSchools_2018_clean.csv\")\n",
    "high_stat = pd.read_csv(\"data/HighSchools_2018_clean.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Get data from csv to lists\n",
    "def get_data(level, school):\n",
    "    \n",
    "    #load the school level data\n",
    "    if level == 'Middle':\n",
    "        school_data = mid_dyn[mid_dyn['dbn']==school]\n",
    "    elif level == 'High':\n",
    "        school_data =  high_dyn[high_dyn['dbn']==school]\n",
    "        \n",
    "    # Convert dataframe to column data source\n",
    "    source = ColumnDataSource(school_data)\n",
    "    \n",
    "    return source, school_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_slider(plot, startYear, endYear):\n",
    "    callback = CustomJS(args=dict(plot=plot), code=\"\"\"\n",
    "    var a = cb_obj.value;\n",
    "    plot.x_range.start = a[0];\n",
    "    plot.x_range.end = a[1];\n",
    "    \"\"\")\n",
    "\n",
    "    range_slider = RangeSlider(start=startYear, end=endYear,value=(startYear, endYear), step=1, width= 600, title=\"Year Range\")\n",
    "    range_slider.js_on_change('value', callback)\n",
    "\n",
    "    layout = column(plot,column(range_slider))\n",
    "    return layout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "def geographic_to_web_mercator(x_lon, y_lat):     \n",
    "    if abs(x_lon) <= 180 and abs(y_lat) < 90:          \n",
    "        num = x_lon * 0.017453292519943295         \n",
    "        x = 6378137.0 * num         \n",
    "        a = y_lat * 0.017453292519943295          \n",
    "        x_mercator = x         \n",
    "        y_mercator = 3189068.5 * np.log((1.0 + np.sin(a)) / (1.0 - np.sin(a)))         \n",
    "        \n",
    "        return x_mercator, y_mercator   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_plot():\n",
    "    colors=['midnightblue','slateblue','dodgerblue','royalblue','cornflowerblue']\n",
    "    radio_idx = radio_group.active\n",
    "    school = text_input.value\n",
    "    \n",
    "    variables = ['Etnicities','Gender','Mean Score (only for middle school)','Graduation/Dropout (only for high shool)']\n",
    "   \n",
    "    if school in mid_stat.dbn.unique():\n",
    "        level='Middle'\n",
    "        text = mid_stat[mid_stat['dbn']==school]['overview'].iloc[0]\n",
    "        data =  mid_stat[mid_stat['dbn']==school]\n",
    "    elif school in high_stat.dbn.unique():\n",
    "        level = 'High'\n",
    "        text = high_stat[high_stat['dbn']==school]['overview'].iloc[0]\n",
    "        data = high_stat[high_stat['dbn']==school]\n",
    "           \n",
    "    src, school_data = get_data(level, school)\n",
    "          \n",
    "    if radio_idx == 0:     \n",
    "        plot = figure(plot_width = 600, plot_height = 500, \n",
    "         toolbar_location=None,\n",
    "        x_axis_label = 'Year', y_axis_label = '% Etnicity')\n",
    "\n",
    "        races = ['asian_rate', 'black_rate', 'hispanic_rate', 'other_rate', 'white_rate','diversity_index']\n",
    "        race_title =['Asian', 'Black', 'Hispanic', 'Other', 'White','Diversity Index']\n",
    "        colors = colors+['gray']\n",
    "        for (race,tit,color) in zip(races,race_title,colors):\n",
    "            line=plot.line('year', race, line_width=2, line_color=color, source=src,legend_label=tit)\n",
    "            plot.circle('year', race, fill_color=color, line_color=color, size=8, source=src)\n",
    "            hover = HoverTool(renderers=[line])\n",
    "            hover.tooltips=[\n",
    "            ('Date', '@year'),\n",
    "            (tit, '@'+race)\n",
    "            ]\n",
    "            plot.add_tools(hover)\n",
    "            \n",
    "        plot.legend.location ='top_left' \n",
    "        plot.add_layout(Title(text= '{} School \\n'.format(level), text_font_style=\"italic\",text_font_size=\"14pt\", align='center'), 'above')\n",
    "        plot.add_layout(Title(text=school_data['school_name'].unique()[0], text_font_size=\"16pt\",align='center'), 'above',)\n",
    "        \n",
    "        #plot.title.align ='center'\n",
    "        #plot.title.text_font_size = \"18px\"\n",
    "        \n",
    "    elif radio_idx == 1:\n",
    "        \n",
    "        plot = figure(plot_width = 600, plot_height = 500, \n",
    "        toolbar_location=None,\n",
    "        x_axis_label = 'Year', y_axis_label = '% Gender')\n",
    "\n",
    "        genders = ['female_rate','male_rate']\n",
    "        gender_title =['Female','Male']\n",
    "        colors = colors[:2]\n",
    "        for (gender,tit,color) in zip(genders,gender_title,colors):\n",
    "            line=plot.line('year', gender, line_width=2, line_color=color, source=src,legend_label=tit)\n",
    "            plot.circle('year', gender, fill_color=color, line_color=color, size=8, source=src)\n",
    "            hover = HoverTool(renderers=[line])\n",
    "            hover.tooltips=[\n",
    "            ('Date', '@year'),\n",
    "            (tit, '@'+gender)\n",
    "            ]\n",
    "            plot.add_tools(hover)\n",
    "       \n",
    "        plot.legend.location ='top_left' \n",
    "        plot.add_layout(Title(text= '{} School \\n'.format(level), text_font_style=\"italic\",text_font_size=\"14pt\", align='center'), 'above')\n",
    "        plot.add_layout(Title(text=school_data['school_name'].unique()[0], text_font_size=\"16pt\",align='center'), 'above',)\n",
    "        \n",
    "\n",
    "        \n",
    "    elif radio_idx == 2 and level == 'Middle':\n",
    "        \n",
    "        plot = figure(plot_width = 600, plot_height = 500, \n",
    "       toolbar_location=None, \n",
    "        x_axis_label = 'Year', y_axis_label = 'Mean Score')\n",
    "        cols = ['mean_score_math', 'mean_score_ela']\n",
    "        cols_tit =  ['Mean Math Score', 'Mean ELA Score']\n",
    "        colors = colors[:2]\n",
    "\n",
    "        for (col,tit,color) in zip(cols,cols_tit,colors):\n",
    "            line=plot.line('year', col, line_width=2, line_color=color, source=src,legend_label=tit)\n",
    "            plot.circle('year', col, fill_color=color, line_color=color, size=8, source=src)\n",
    "            hover = HoverTool(renderers=[line])\n",
    "            hover.tooltips=[\n",
    "                ('Date', '@year'),\n",
    "                (tit, '@'+col)\n",
    "            ]\n",
    "            plot.add_tools(hover)\n",
    "        \n",
    "        plot.legend.location ='top_left' \n",
    "        plot.add_layout(Title(text= '{} School \\n'.format(level), text_font_style=\"italic\",text_font_size=\"14pt\", align='center'), 'above')\n",
    "        plot.add_layout(Title(text=school_data['school_name'].unique()[0], text_font_size=\"16pt\",align='center'), 'above',)\n",
    "        \n",
    "\n",
    "    elif radio_idx == 3 and level=='High':\n",
    "        \n",
    "        plot = figure(plot_width = 600, plot_height = 500, \n",
    "       toolbar_location=None, \n",
    "        x_axis_label = 'Year', y_axis_label = 'Graduation/Dropout')\n",
    "        cols = ['dropout_rate', 'graduation_rate']\n",
    "        cols_tit =  ['Dropout Rate', 'Graduation Rate']\n",
    "        colors = colors[:2]\n",
    "\n",
    "        for (col,tit,color) in zip(cols,cols_tit,colors):\n",
    "            line=plot.line('year', col, line_width=2, line_color=color, source=src,legend_label=tit)\n",
    "            plot.circle('year', col, fill_color=color, line_color=color, size=8, source=src)\n",
    "            hover = HoverTool(renderers=[line])\n",
    "            hover.tooltips=[\n",
    "                ('Date', '@year'),\n",
    "                (tit, '@'+col)\n",
    "            ]\n",
    "            plot.add_tools(hover)\n",
    "        \n",
    "        plot.legend.location ='top_left' \n",
    "        plot.add_layout(Title(text= '{} School \\n'.format(level), text_font_style=\"italic\",text_font_size=\"14pt\", align='center'), 'above')\n",
    "        plot.add_layout(Title(text=school_data['school_name'].unique()[0], text_font_size=\"16pt\",align='center'), 'above',)\n",
    "        \n",
    "\n",
    "        \n",
    "    elif (radio_idx == 3 and level != 'High') or (radio_idx == 2 and level != 'Middle'):\n",
    "        \n",
    "        plot = figure(plot_width = 600, plot_height = 500, \n",
    "       toolbar_location=None, \n",
    "        x_axis_label = '', y_axis_label = '')\n",
    "        \n",
    "        if level=='High':\n",
    "            l = 'Middle'\n",
    "        elif level=='Middle':\n",
    "            l = 'High'\n",
    "        \n",
    "        \n",
    "        citation = Label(x=170, y=250, x_units='screen', y_units='screen',\n",
    "                 text='Only available for {} Schools'.format(l), render_mode='css',\n",
    "                 background_fill_color='white', background_fill_alpha=1.0,text_font_size='20px')\n",
    "        \n",
    "        plot.add_layout(citation)\n",
    "        \n",
    "        plot.legend.location ='top_left' \n",
    "        #plot.add_layout(Title(text= '{} School \\n'.format(level), text_font_style=\"italic\",text_font_size=\"14pt\", align='center'), 'above')\n",
    "        plot.add_layout(Title(text=school_data['school_name'].unique()[0], text_font_size=\"16pt\",align='center'), 'above',)\n",
    "        \n",
    "\n",
    "   \n",
    "    #Add overview paragraph\n",
    "    para = Div(text=\"<h2>Overview</h2>\"+text,\n",
    "    width=300, height=100)\n",
    "    \n",
    "    #Get map\n",
    "    x,y = geographic_to_web_mercator(data['lon'].iloc[0],data['lat'].iloc[0])\n",
    "    tile_provider = get_provider(CARTODBPOSITRON)\n",
    "    # range bounds supplied in web mercator coordinates\n",
    "    m = figure(x_range=(x-500, x+500), y_range=(y-500, y+500),height=300,width=300, \n",
    "               x_axis_location=None, y_axis_location=None,toolbar_location='below',tools=\"pan,wheel_zoom,reset\",active_scroll='auto')\n",
    "    m.add_tile(tile_provider)\n",
    "    square=m.circle(x=x,y=y,size=12, fill_color=\"midnightblue\", fill_alpha=1)\n",
    "    tooltips = [('Name', data['school_name'].iloc[0]),('Address', data['address'].iloc[0])]\n",
    "    m.add_tools(HoverTool(renderers=[square],tooltips=tooltips))\n",
    "\n",
    "\n",
    "    return plot, para, m\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "    <div class=\"bk-root\">\n",
       "        <a href=\"https://bokeh.org\" target=\"_blank\" class=\"bk-logo bk-logo-small bk-logo-notebook\"></a>\n",
       "        <span id=\"5533\">Loading BokehJS ...</span>\n",
       "    </div>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/javascript": [
       "\n",
       "(function(root) {\n",
       "  function now() {\n",
       "    return new Date();\n",
       "  }\n",
       "\n",
       "  var force = true;\n",
       "\n",
       "  if (typeof root._bokeh_onload_callbacks === \"undefined\" || force === true) {\n",
       "    root._bokeh_onload_callbacks = [];\n",
       "    root._bokeh_is_loading = undefined;\n",
       "  }\n",
       "\n",
       "  var JS_MIME_TYPE = 'application/javascript';\n",
       "  var HTML_MIME_TYPE = 'text/html';\n",
       "  var EXEC_MIME_TYPE = 'application/vnd.bokehjs_exec.v0+json';\n",
       "  var CLASS_NAME = 'output_bokeh rendered_html';\n",
       "\n",
       "  /**\n",
       "   * Render data to the DOM node\n",
       "   */\n",
       "  function render(props, node) {\n",
       "    var script = document.createElement(\"script\");\n",
       "    node.appendChild(script);\n",
       "  }\n",
       "\n",
       "  /**\n",
       "   * Handle when an output is cleared or removed\n",
       "   */\n",
       "  function handleClearOutput(event, handle) {\n",
       "    var cell = handle.cell;\n",
       "\n",
       "    var id = cell.output_area._bokeh_element_id;\n",
       "    var server_id = cell.output_area._bokeh_server_id;\n",
       "    // Clean up Bokeh references\n",
       "    if (id != null && id in Bokeh.index) {\n",
       "      Bokeh.index[id].model.document.clear();\n",
       "      delete Bokeh.index[id];\n",
       "    }\n",
       "\n",
       "    if (server_id !== undefined) {\n",
       "      // Clean up Bokeh references\n",
       "      var cmd = \"from bokeh.io.state import curstate; print(curstate().uuid_to_server['\" + server_id + \"'].get_sessions()[0].document.roots[0]._id)\";\n",
       "      cell.notebook.kernel.execute(cmd, {\n",
       "        iopub: {\n",
       "          output: function(msg) {\n",
       "            var id = msg.content.text.trim();\n",
       "            if (id in Bokeh.index) {\n",
       "              Bokeh.index[id].model.document.clear();\n",
       "              delete Bokeh.index[id];\n",
       "            }\n",
       "          }\n",
       "        }\n",
       "      });\n",
       "      // Destroy server and session\n",
       "      var cmd = \"import bokeh.io.notebook as ion; ion.destroy_server('\" + server_id + \"')\";\n",
       "      cell.notebook.kernel.execute(cmd);\n",
       "    }\n",
       "  }\n",
       "\n",
       "  /**\n",
       "   * Handle when a new output is added\n",
       "   */\n",
       "  function handleAddOutput(event, handle) {\n",
       "    var output_area = handle.output_area;\n",
       "    var output = handle.output;\n",
       "\n",
       "    // limit handleAddOutput to display_data with EXEC_MIME_TYPE content only\n",
       "    if ((output.output_type != \"display_data\") || (!output.data.hasOwnProperty(EXEC_MIME_TYPE))) {\n",
       "      return\n",
       "    }\n",
       "\n",
       "    var toinsert = output_area.element.find(\".\" + CLASS_NAME.split(' ')[0]);\n",
       "\n",
       "    if (output.metadata[EXEC_MIME_TYPE][\"id\"] !== undefined) {\n",
       "      toinsert[toinsert.length - 1].firstChild.textContent = output.data[JS_MIME_TYPE];\n",
       "      // store reference to embed id on output_area\n",
       "      output_area._bokeh_element_id = output.metadata[EXEC_MIME_TYPE][\"id\"];\n",
       "    }\n",
       "    if (output.metadata[EXEC_MIME_TYPE][\"server_id\"] !== undefined) {\n",
       "      var bk_div = document.createElement(\"div\");\n",
       "      bk_div.innerHTML = output.data[HTML_MIME_TYPE];\n",
       "      var script_attrs = bk_div.children[0].attributes;\n",
       "      for (var i = 0; i < script_attrs.length; i++) {\n",
       "        toinsert[toinsert.length - 1].firstChild.setAttribute(script_attrs[i].name, script_attrs[i].value);\n",
       "        toinsert[toinsert.length - 1].firstChild.textContent = bk_div.children[0].textContent\n",
       "      }\n",
       "      // store reference to server id on output_area\n",
       "      output_area._bokeh_server_id = output.metadata[EXEC_MIME_TYPE][\"server_id\"];\n",
       "    }\n",
       "  }\n",
       "\n",
       "  function register_renderer(events, OutputArea) {\n",
       "\n",
       "    function append_mime(data, metadata, element) {\n",
       "      // create a DOM node to render to\n",
       "      var toinsert = this.create_output_subarea(\n",
       "        metadata,\n",
       "        CLASS_NAME,\n",
       "        EXEC_MIME_TYPE\n",
       "      );\n",
       "      this.keyboard_manager.register_events(toinsert);\n",
       "      // Render to node\n",
       "      var props = {data: data, metadata: metadata[EXEC_MIME_TYPE]};\n",
       "      render(props, toinsert[toinsert.length - 1]);\n",
       "      element.append(toinsert);\n",
       "      return toinsert\n",
       "    }\n",
       "\n",
       "    /* Handle when an output is cleared or removed */\n",
       "    events.on('clear_output.CodeCell', handleClearOutput);\n",
       "    events.on('delete.Cell', handleClearOutput);\n",
       "\n",
       "    /* Handle when a new output is added */\n",
       "    events.on('output_added.OutputArea', handleAddOutput);\n",
       "\n",
       "    /**\n",
       "     * Register the mime type and append_mime function with output_area\n",
       "     */\n",
       "    OutputArea.prototype.register_mime_type(EXEC_MIME_TYPE, append_mime, {\n",
       "      /* Is output safe? */\n",
       "      safe: true,\n",
       "      /* Index of renderer in `output_area.display_order` */\n",
       "      index: 0\n",
       "    });\n",
       "  }\n",
       "\n",
       "  // register the mime type if in Jupyter Notebook environment and previously unregistered\n",
       "  if (root.Jupyter !== undefined) {\n",
       "    var events = require('base/js/events');\n",
       "    var OutputArea = require('notebook/js/outputarea').OutputArea;\n",
       "\n",
       "    if (OutputArea.prototype.mime_types().indexOf(EXEC_MIME_TYPE) == -1) {\n",
       "      register_renderer(events, OutputArea);\n",
       "    }\n",
       "  }\n",
       "\n",
       "  \n",
       "  if (typeof (root._bokeh_timeout) === \"undefined\" || force === true) {\n",
       "    root._bokeh_timeout = Date.now() + 5000;\n",
       "    root._bokeh_failed_load = false;\n",
       "  }\n",
       "\n",
       "  var NB_LOAD_WARNING = {'data': {'text/html':\n",
       "     \"<div style='background-color: #fdd'>\\n\"+\n",
       "     \"<p>\\n\"+\n",
       "     \"BokehJS does not appear to have successfully loaded. If loading BokehJS from CDN, this \\n\"+\n",
       "     \"may be due to a slow or bad network connection. Possible fixes:\\n\"+\n",
       "     \"</p>\\n\"+\n",
       "     \"<ul>\\n\"+\n",
       "     \"<li>re-rerun `output_notebook()` to attempt to load from CDN again, or</li>\\n\"+\n",
       "     \"<li>use INLINE resources instead, as so:</li>\\n\"+\n",
       "     \"</ul>\\n\"+\n",
       "     \"<code>\\n\"+\n",
       "     \"from bokeh.resources import INLINE\\n\"+\n",
       "     \"output_notebook(resources=INLINE)\\n\"+\n",
       "     \"</code>\\n\"+\n",
       "     \"</div>\"}};\n",
       "\n",
       "  function display_loaded() {\n",
       "    var el = document.getElementById(\"5533\");\n",
       "    if (el != null) {\n",
       "      el.textContent = \"BokehJS is loading...\";\n",
       "    }\n",
       "    if (root.Bokeh !== undefined) {\n",
       "      if (el != null) {\n",
       "        el.textContent = \"BokehJS \" + root.Bokeh.version + \" successfully loaded.\";\n",
       "      }\n",
       "    } else if (Date.now() < root._bokeh_timeout) {\n",
       "      setTimeout(display_loaded, 100)\n",
       "    }\n",
       "  }\n",
       "\n",
       "\n",
       "  function run_callbacks() {\n",
       "    try {\n",
       "      root._bokeh_onload_callbacks.forEach(function(callback) {\n",
       "        if (callback != null)\n",
       "          callback();\n",
       "      });\n",
       "    } finally {\n",
       "      delete root._bokeh_onload_callbacks\n",
       "    }\n",
       "    console.debug(\"Bokeh: all callbacks have finished\");\n",
       "  }\n",
       "\n",
       "  function load_libs(css_urls, js_urls, callback) {\n",
       "    if (css_urls == null) css_urls = [];\n",
       "    if (js_urls == null) js_urls = [];\n",
       "\n",
       "    root._bokeh_onload_callbacks.push(callback);\n",
       "    if (root._bokeh_is_loading > 0) {\n",
       "      console.debug(\"Bokeh: BokehJS is being loaded, scheduling callback at\", now());\n",
       "      return null;\n",
       "    }\n",
       "    if (js_urls == null || js_urls.length === 0) {\n",
       "      run_callbacks();\n",
       "      return null;\n",
       "    }\n",
       "    console.debug(\"Bokeh: BokehJS not loaded, scheduling load and callback at\", now());\n",
       "    root._bokeh_is_loading = css_urls.length + js_urls.length;\n",
       "\n",
       "    function on_load() {\n",
       "      root._bokeh_is_loading--;\n",
       "      if (root._bokeh_is_loading === 0) {\n",
       "        console.debug(\"Bokeh: all BokehJS libraries/stylesheets loaded\");\n",
       "        run_callbacks()\n",
       "      }\n",
       "    }\n",
       "\n",
       "    function on_error() {\n",
       "      console.error(\"failed to load \" + url);\n",
       "    }\n",
       "\n",
       "    for (var i = 0; i < css_urls.length; i++) {\n",
       "      var url = css_urls[i];\n",
       "      const element = document.createElement(\"link\");\n",
       "      element.onload = on_load;\n",
       "      element.onerror = on_error;\n",
       "      element.rel = \"stylesheet\";\n",
       "      element.type = \"text/css\";\n",
       "      element.href = url;\n",
       "      console.debug(\"Bokeh: injecting link tag for BokehJS stylesheet: \", url);\n",
       "      document.body.appendChild(element);\n",
       "    }\n",
       "\n",
       "    const hashes = {\"https://cdn.bokeh.org/bokeh/release/bokeh-2.0.1.min.js\": \"JpP8FXbgAZLkfur7LiK3j9AGBhHNIvF742meBJrjO2ShJDhCG2I1uVvW+0DUtrmc\", \"https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.0.1.min.js\": \"xZlADit0Q04ISQEdKg2k3L4W9AwQBAuDs9nJL9fM/WwzL1tEU9VPNezOFX0nLEAz\", \"https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.0.1.min.js\": \"4BuPRZkdMKSnj3zoxiNrQ86XgNw0rYmBOxe7nshquXwwcauupgBF2DHLVG1WuZlV\", \"https://cdn.bokeh.org/bokeh/release/bokeh-gl-2.0.1.min.js\": \"Dv1SQ87hmDqK6S5OhBf0bCuwAEvL5QYL0PuR/F1SPVhCS/r/abjkbpKDYL2zeM19\"};\n",
       "\n",
       "    for (var i = 0; i < js_urls.length; i++) {\n",
       "      var url = js_urls[i];\n",
       "      var element = document.createElement('script');\n",
       "      element.onload = on_load;\n",
       "      element.onerror = on_error;\n",
       "      element.async = false;\n",
       "      element.src = url;\n",
       "      if (url in hashes) {\n",
       "        element.crossOrigin = \"anonymous\";\n",
       "        element.integrity = \"sha384-\" + hashes[url];\n",
       "      }\n",
       "      console.debug(\"Bokeh: injecting script tag for BokehJS library: \", url);\n",
       "      document.head.appendChild(element);\n",
       "    }\n",
       "  };var element = document.getElementById(\"5533\");\n",
       "  if (element == null) {\n",
       "    console.error(\"Bokeh: ERROR: autoload.js configured with elementid '5533' but no matching script tag was found. \")\n",
       "    return false;\n",
       "  }\n",
       "\n",
       "  function inject_raw_css(css) {\n",
       "    const element = document.createElement(\"style\");\n",
       "    element.appendChild(document.createTextNode(css));\n",
       "    document.body.appendChild(element);\n",
       "  }\n",
       "\n",
       "  \n",
       "  var js_urls = [\"https://cdn.bokeh.org/bokeh/release/bokeh-2.0.1.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.0.1.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.0.1.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-gl-2.0.1.min.js\"];\n",
       "  var css_urls = [];\n",
       "  \n",
       "\n",
       "  var inline_js = [\n",
       "    function(Bokeh) {\n",
       "      Bokeh.set_log_level(\"info\");\n",
       "    },\n",
       "    function(Bokeh) {\n",
       "    \n",
       "    \n",
       "    }\n",
       "  ];\n",
       "\n",
       "  function run_inline_js() {\n",
       "    \n",
       "    if (root.Bokeh !== undefined || force === true) {\n",
       "      \n",
       "    for (var i = 0; i < inline_js.length; i++) {\n",
       "      inline_js[i].call(root, root.Bokeh);\n",
       "    }\n",
       "    if (force === true) {\n",
       "        display_loaded();\n",
       "      }} else if (Date.now() < root._bokeh_timeout) {\n",
       "      setTimeout(run_inline_js, 100);\n",
       "    } else if (!root._bokeh_failed_load) {\n",
       "      console.log(\"Bokeh: BokehJS failed to load within specified timeout.\");\n",
       "      root._bokeh_failed_load = true;\n",
       "    } else if (force !== true) {\n",
       "      var cell = $(document.getElementById(\"5533\")).parents('.cell').data().cell;\n",
       "      cell.output_area.append_execute_result(NB_LOAD_WARNING)\n",
       "    }\n",
       "\n",
       "  }\n",
       "\n",
       "  if (root._bokeh_is_loading === 0) {\n",
       "    console.debug(\"Bokeh: BokehJS loaded, going straight to plotting\");\n",
       "    run_inline_js();\n",
       "  } else {\n",
       "    load_libs(css_urls, js_urls, function() {\n",
       "      console.debug(\"Bokeh: BokehJS plotting callback run at\", now());\n",
       "      run_inline_js();\n",
       "    });\n",
       "  }\n",
       "}(window));"
      ],
      "application/vnd.bokehjs_load.v0+json": "\n(function(root) {\n  function now() {\n    return new Date();\n  }\n\n  var force = true;\n\n  if (typeof root._bokeh_onload_callbacks === \"undefined\" || force === true) {\n    root._bokeh_onload_callbacks = [];\n    root._bokeh_is_loading = undefined;\n  }\n\n  \n\n  \n  if (typeof (root._bokeh_timeout) === \"undefined\" || force === true) {\n    root._bokeh_timeout = Date.now() + 5000;\n    root._bokeh_failed_load = false;\n  }\n\n  var NB_LOAD_WARNING = {'data': {'text/html':\n     \"<div style='background-color: #fdd'>\\n\"+\n     \"<p>\\n\"+\n     \"BokehJS does not appear to have successfully loaded. If loading BokehJS from CDN, this \\n\"+\n     \"may be due to a slow or bad network connection. Possible fixes:\\n\"+\n     \"</p>\\n\"+\n     \"<ul>\\n\"+\n     \"<li>re-rerun `output_notebook()` to attempt to load from CDN again, or</li>\\n\"+\n     \"<li>use INLINE resources instead, as so:</li>\\n\"+\n     \"</ul>\\n\"+\n     \"<code>\\n\"+\n     \"from bokeh.resources import INLINE\\n\"+\n     \"output_notebook(resources=INLINE)\\n\"+\n     \"</code>\\n\"+\n     \"</div>\"}};\n\n  function display_loaded() {\n    var el = document.getElementById(\"5533\");\n    if (el != null) {\n      el.textContent = \"BokehJS is loading...\";\n    }\n    if (root.Bokeh !== undefined) {\n      if (el != null) {\n        el.textContent = \"BokehJS \" + root.Bokeh.version + \" successfully loaded.\";\n      }\n    } else if (Date.now() < root._bokeh_timeout) {\n      setTimeout(display_loaded, 100)\n    }\n  }\n\n\n  function run_callbacks() {\n    try {\n      root._bokeh_onload_callbacks.forEach(function(callback) {\n        if (callback != null)\n          callback();\n      });\n    } finally {\n      delete root._bokeh_onload_callbacks\n    }\n    console.debug(\"Bokeh: all callbacks have finished\");\n  }\n\n  function load_libs(css_urls, js_urls, callback) {\n    if (css_urls == null) css_urls = [];\n    if (js_urls == null) js_urls = [];\n\n    root._bokeh_onload_callbacks.push(callback);\n    if (root._bokeh_is_loading > 0) {\n      console.debug(\"Bokeh: BokehJS is being loaded, scheduling callback at\", now());\n      return null;\n    }\n    if (js_urls == null || js_urls.length === 0) {\n      run_callbacks();\n      return null;\n    }\n    console.debug(\"Bokeh: BokehJS not loaded, scheduling load and callback at\", now());\n    root._bokeh_is_loading = css_urls.length + js_urls.length;\n\n    function on_load() {\n      root._bokeh_is_loading--;\n      if (root._bokeh_is_loading === 0) {\n        console.debug(\"Bokeh: all BokehJS libraries/stylesheets loaded\");\n        run_callbacks()\n      }\n    }\n\n    function on_error() {\n      console.error(\"failed to load \" + url);\n    }\n\n    for (var i = 0; i < css_urls.length; i++) {\n      var url = css_urls[i];\n      const element = document.createElement(\"link\");\n      element.onload = on_load;\n      element.onerror = on_error;\n      element.rel = \"stylesheet\";\n      element.type = \"text/css\";\n      element.href = url;\n      console.debug(\"Bokeh: injecting link tag for BokehJS stylesheet: \", url);\n      document.body.appendChild(element);\n    }\n\n    const hashes = {\"https://cdn.bokeh.org/bokeh/release/bokeh-2.0.1.min.js\": \"JpP8FXbgAZLkfur7LiK3j9AGBhHNIvF742meBJrjO2ShJDhCG2I1uVvW+0DUtrmc\", \"https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.0.1.min.js\": \"xZlADit0Q04ISQEdKg2k3L4W9AwQBAuDs9nJL9fM/WwzL1tEU9VPNezOFX0nLEAz\", \"https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.0.1.min.js\": \"4BuPRZkdMKSnj3zoxiNrQ86XgNw0rYmBOxe7nshquXwwcauupgBF2DHLVG1WuZlV\", \"https://cdn.bokeh.org/bokeh/release/bokeh-gl-2.0.1.min.js\": \"Dv1SQ87hmDqK6S5OhBf0bCuwAEvL5QYL0PuR/F1SPVhCS/r/abjkbpKDYL2zeM19\"};\n\n    for (var i = 0; i < js_urls.length; i++) {\n      var url = js_urls[i];\n      var element = document.createElement('script');\n      element.onload = on_load;\n      element.onerror = on_error;\n      element.async = false;\n      element.src = url;\n      if (url in hashes) {\n        element.crossOrigin = \"anonymous\";\n        element.integrity = \"sha384-\" + hashes[url];\n      }\n      console.debug(\"Bokeh: injecting script tag for BokehJS library: \", url);\n      document.head.appendChild(element);\n    }\n  };var element = document.getElementById(\"5533\");\n  if (element == null) {\n    console.error(\"Bokeh: ERROR: autoload.js configured with elementid '5533' but no matching script tag was found. \")\n    return false;\n  }\n\n  function inject_raw_css(css) {\n    const element = document.createElement(\"style\");\n    element.appendChild(document.createTextNode(css));\n    document.body.appendChild(element);\n  }\n\n  \n  var js_urls = [\"https://cdn.bokeh.org/bokeh/release/bokeh-2.0.1.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.0.1.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.0.1.min.js\", \"https://cdn.bokeh.org/bokeh/release/bokeh-gl-2.0.1.min.js\"];\n  var css_urls = [];\n  \n\n  var inline_js = [\n    function(Bokeh) {\n      Bokeh.set_log_level(\"info\");\n    },\n    function(Bokeh) {\n    \n    \n    }\n  ];\n\n  function run_inline_js() {\n    \n    if (root.Bokeh !== undefined || force === true) {\n      \n    for (var i = 0; i < inline_js.length; i++) {\n      inline_js[i].call(root, root.Bokeh);\n    }\n    if (force === true) {\n        display_loaded();\n      }} else if (Date.now() < root._bokeh_timeout) {\n      setTimeout(run_inline_js, 100);\n    } else if (!root._bokeh_failed_load) {\n      console.log(\"Bokeh: BokehJS failed to load within specified timeout.\");\n      root._bokeh_failed_load = true;\n    } else if (force !== true) {\n      var cell = $(document.getElementById(\"5533\")).parents('.cell').data().cell;\n      cell.output_area.append_execute_result(NB_LOAD_WARNING)\n    }\n\n  }\n\n  if (root._bokeh_is_loading === 0) {\n    console.debug(\"Bokeh: BokehJS loaded, going straight to plotting\");\n    run_inline_js();\n  } else {\n    load_libs(css_urls, js_urls, function() {\n      console.debug(\"Bokeh: BokehJS plotting callback run at\", now());\n      run_inline_js();\n    });\n  }\n}(window));"
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:bokeh.embed.util:\n",
      "You are generating standalone HTML/JS output, but trying to use real Python\n",
      "callbacks (i.e. with on_change or on_event). This combination cannot work.\n",
      "\n",
      "Only JavaScript callbacks may be used with standalone output. For more\n",
      "information on JavaScript callbacks with Bokeh, see:\n",
      "\n",
      "    https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html\n",
      "\n",
      "Alternatively, to use real Python callbacks, a Bokeh server application may\n",
      "be used. For more information on building and running Bokeh applications, see:\n",
      "\n",
      "    https://docs.bokeh.org/en/latest/docs/user_guide/server.html\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "\n",
       "\n",
       "\n",
       "\n",
       "\n",
       "  <div class=\"bk-root\" id=\"d56cda7f-3cb1-4ecf-8bbb-1a0a5796bc0f\" data-root-id=\"5395\"></div>\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/javascript": [
       "(function(root) {\n",
       "  function embed_document(root) {\n",
       "    \n",
       "  var docs_json = {\"649a2270-4e3f-4898-be67-1bf41ea293a7\":{\"roots\":{\"references\":[{\"attributes\":{\"children\":[{\"id\":\"5394\"},{\"id\":\"5393\"},{\"id\":\"5355\"}]},\"id\":\"5395\",\"type\":\"Row\"},{\"attributes\":{\"axis\":{\"id\":\"5370\"},\"dimension\":1,\"ticker\":null},\"id\":\"5373\",\"type\":\"Grid\"},{\"attributes\":{\"active_drag\":\"auto\",\"active_inspect\":\"auto\",\"active_multi\":null,\"active_scroll\":\"auto\",\"active_tap\":\"auto\",\"tools\":[{\"id\":\"5374\"},{\"id\":\"5375\"},{\"id\":\"5376\"},{\"id\":\"5388\"}]},\"id\":\"5377\",\"type\":\"Toolbar\"},{\"attributes\":{},\"id\":\"5325\",\"type\":\"DataRange1d\"},{\"attributes\":{\"end\":2018,\"format\":\"0[.]00\",\"js_property_callbacks\":{\"change:value\":[{\"id\":\"5390\"}]},\"start\":2006,\"title\":\"Year Range\",\"value\":[2006,2018],\"width\":600},\"id\":\"5391\",\"type\":\"RangeSlider\"},{\"attributes\":{\"data\":{},\"selected\":{\"id\":\"5531\"},\"selection_policy\":{\"id\":\"5530\"}},\"id\":\"5383\",\"type\":\"ColumnDataSource\"},{\"attributes\":{},\"id\":\"5344\",\"type\":\"HelpTool\"},{\"attributes\":{},\"id\":\"5530\",\"type\":\"UnionRenderers\"},{\"attributes\":{\"formatter\":{\"id\":\"5523\"},\"ticker\":{\"id\":\"5336\"}},\"id\":\"5335\",\"type\":\"LinearAxis\"},{\"attributes\":{\"background_fill_color\":\"white\",\"render_mode\":\"css\",\"text\":\"Only available for High Schools\",\"text_font_size\":\"20px\",\"x\":170,\"x_units\":\"screen\",\"y\":250,\"y_units\":\"screen\"},\"id\":\"5353\",\"type\":\"Label\"},{\"attributes\":{},\"id\":\"5339\",\"type\":\"PanTool\"},{\"attributes\":{\"height\":100,\"text\":\"<h2>Overview</h2>We are a community of learners focused on success. We encourage our students to take risks, to try their best, and to take advantage of the opportunities offered at our school. We take pride in the small school community. The students say: \\\"The teachers are very understanding and supportive. They care about us and point us in the right direction.\\\" In order to meet the Common Core Standards, the curricula used are Scholastic Code-X for ELA and Pearson CMP3 for Math. In social studies and science courses, we focus on project-based learning. We have a technology lab, science lab, and a fully equipped gymnasium. Our students have a variety of leadership opportunities through student council, safety patrol, and book buddies with the lower grades. In addition, our students receive small group support and/or elective on alternating days. Our students have the opportunity to participate in a variety of after-school programs funded by the 21st Century and community-based organizations.\",\"width\":300},\"id\":\"5355\",\"type\":\"Div\"},{\"attributes\":{\"text\":\"<b> Write School DBN </b>\"},\"id\":\"5317\",\"type\":\"Div\"},{\"attributes\":{},\"id\":\"5367\",\"type\":\"BasicTicker\"},{\"attributes\":{},\"id\":\"5323\",\"type\":\"DataRange1d\"},{\"attributes\":{},\"id\":\"5523\",\"type\":\"BasicTickFormatter\"},{\"attributes\":{\"bottom_units\":\"screen\",\"fill_alpha\":0.5,\"fill_color\":\"lightgrey\",\"left_units\":\"screen\",\"level\":\"overlay\",\"line_alpha\":1.0,\"line_color\":\"black\",\"line_dash\":[4,4],\"line_width\":2,\"render_mode\":\"css\",\"right_units\":\"screen\",\"top_units\":\"screen\"},\"id\":\"5345\",\"type\":\"BoxAnnotation\"},{\"attributes\":{},\"id\":\"5327\",\"type\":\"LinearScale\"},{\"attributes\":{\"text\":\"<b> School Location </b>\"},\"id\":\"5320\",\"type\":\"Div\"},{\"attributes\":{},\"id\":\"5362\",\"type\":\"LinearScale\"},{\"attributes\":{\"formatter\":{\"id\":\"5527\"},\"ticker\":{\"id\":\"5367\"}},\"id\":\"5366\",\"type\":\"LinearAxis\"},{\"attributes\":{\"align\":\"center\",\"text\":\"P.S. 140 Nathan Straus\",\"text_font_size\":{\"value\":\"16pt\"}},\"id\":\"5354\",\"type\":\"Title\"},{\"attributes\":{},\"id\":\"5343\",\"type\":\"ResetTool\"},{\"attributes\":{\"active\":3,\"labels\":[\"Etnicities\",\"Gender\",\"Mean Score (only middle schools)\",\"Graduation/Dropout (only high shools)\"]},\"id\":\"5319\",\"type\":\"RadioGroup\"},{\"attributes\":{\"end\":4971518.882917135,\"start\":4970518.882917135},\"id\":\"5360\",\"type\":\"Range1d\"},{\"attributes\":{\"tile_source\":{\"id\":\"5356\"}},\"id\":\"5381\",\"type\":\"TileRenderer\"},{\"attributes\":{\"end\":-8235256.121250243,\"start\":-8236256.121250243},\"id\":\"5358\",\"type\":\"Range1d\"},{\"attributes\":{\"above\":[{\"id\":\"5354\"}],\"below\":[{\"id\":\"5331\"}],\"center\":[{\"id\":\"5334\"},{\"id\":\"5338\"},{\"id\":\"5353\"}],\"left\":[{\"id\":\"5335\"}],\"plot_height\":500,\"title\":{\"id\":\"5521\"},\"toolbar\":{\"id\":\"5346\"},\"toolbar_location\":null,\"x_range\":{\"id\":\"5323\"},\"x_scale\":{\"id\":\"5327\"},\"y_range\":{\"id\":\"5325\"},\"y_scale\":{\"id\":\"5329\"}},\"id\":\"5322\",\"subtype\":\"Figure\",\"type\":\"Plot\"},{\"attributes\":{},\"id\":\"5527\",\"type\":\"BasicTickFormatter\"},{\"attributes\":{},\"id\":\"5329\",\"type\":\"LinearScale\"},{\"attributes\":{\"active_drag\":\"auto\",\"active_inspect\":\"auto\",\"active_multi\":null,\"active_scroll\":\"auto\",\"active_tap\":\"auto\",\"tools\":[{\"id\":\"5339\"},{\"id\":\"5340\"},{\"id\":\"5341\"},{\"id\":\"5342\"},{\"id\":\"5343\"},{\"id\":\"5344\"}]},\"id\":\"5346\",\"type\":\"Toolbar\"},{\"attributes\":{\"text\":\"\"},\"id\":\"5521\",\"type\":\"Title\"},{\"attributes\":{},\"id\":\"5374\",\"type\":\"PanTool\"},{\"attributes\":{\"overlay\":{\"id\":\"5345\"}},\"id\":\"5341\",\"type\":\"BoxZoomTool\"},{\"attributes\":{\"formatter\":{\"id\":\"5529\"},\"ticker\":{\"id\":\"5371\"}},\"id\":\"5370\",\"type\":\"LinearAxis\"},{\"attributes\":{\"args\":{\"plot\":{\"id\":\"5322\"}},\"code\":\"\\n    var a = cb_obj.value;\\n    plot.x_range.start = a[0];\\n    plot.x_range.end = a[1];\\n    \"},\"id\":\"5390\",\"type\":\"CustomJS\"},{\"attributes\":{\"fill_alpha\":{\"value\":0.1},\"fill_color\":{\"value\":\"midnightblue\"},\"line_alpha\":{\"value\":0.1},\"line_color\":{\"value\":\"#1f77b4\"},\"size\":{\"units\":\"screen\",\"value\":12},\"x\":{\"value\":-8235756.121250243},\"y\":{\"value\":4971018.882917135}},\"id\":\"5385\",\"type\":\"Circle\"},{\"attributes\":{\"text\":\"\"},\"id\":\"5519\",\"type\":\"Title\"},{\"attributes\":{\"attribution\":\"&copy; <a href=\\\"https://www.openstreetmap.org/copyright\\\">OpenStreetMap</a> contributors,&copy; <a href=\\\"https://cartodb.com/attributions\\\">CartoDB</a>\",\"url\":\"https://tiles.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png\"},\"id\":\"5356\",\"type\":\"WMTSTileSource\"},{\"attributes\":{\"value\":\"01M140\"},\"id\":\"5316\",\"type\":\"TextInput\"},{\"attributes\":{\"axis\":{\"id\":\"5366\"},\"ticker\":null},\"id\":\"5369\",\"type\":\"Grid\"},{\"attributes\":{\"source\":{\"id\":\"5383\"}},\"id\":\"5387\",\"type\":\"CDSView\"},{\"attributes\":{\"callback\":null,\"renderers\":[{\"id\":\"5386\"}],\"tooltips\":[[\"Name\",\"P.S. 140 Nathan Straus\"],[\"Address\",\"123 Ridge Street, Manhattan NY 10002\"]]},\"id\":\"5388\",\"type\":\"HoverTool\"},{\"attributes\":{},\"id\":\"5364\",\"type\":\"LinearScale\"},{\"attributes\":{\"formatter\":{\"id\":\"5525\"},\"ticker\":{\"id\":\"5332\"}},\"id\":\"5331\",\"type\":\"LinearAxis\"},{\"attributes\":{},\"id\":\"5375\",\"type\":\"WheelZoomTool\"},{\"attributes\":{},\"id\":\"5336\",\"type\":\"BasicTicker\"},{\"attributes\":{},\"id\":\"5332\",\"type\":\"BasicTicker\"},{\"attributes\":{},\"id\":\"5531\",\"type\":\"Selection\"},{\"attributes\":{\"children\":[{\"id\":\"5317\"},{\"id\":\"5316\"},{\"id\":\"5318\"},{\"id\":\"5319\"},{\"id\":\"5320\"},{\"id\":\"5357\"}],\"width\":300},\"id\":\"5394\",\"type\":\"Column\"},{\"attributes\":{},\"id\":\"5529\",\"type\":\"BasicTickFormatter\"},{\"attributes\":{\"axis\":{\"id\":\"5335\"},\"dimension\":1,\"ticker\":null},\"id\":\"5338\",\"type\":\"Grid\"},{\"attributes\":{},\"id\":\"5376\",\"type\":\"ResetTool\"},{\"attributes\":{},\"id\":\"5342\",\"type\":\"SaveTool\"},{\"attributes\":{},\"id\":\"5371\",\"type\":\"BasicTicker\"},{\"attributes\":{\"data_source\":{\"id\":\"5383\"},\"glyph\":{\"id\":\"5384\"},\"hover_glyph\":null,\"muted_glyph\":null,\"nonselection_glyph\":{\"id\":\"5385\"},\"selection_glyph\":null,\"view\":{\"id\":\"5387\"}},\"id\":\"5386\",\"type\":\"GlyphRenderer\"},{\"attributes\":{\"children\":[{\"id\":\"5391\"}]},\"id\":\"5392\",\"type\":\"Column\"},{\"attributes\":{},\"id\":\"5525\",\"type\":\"BasicTickFormatter\"},{\"attributes\":{\"children\":[{\"id\":\"5322\"},{\"id\":\"5392\"}]},\"id\":\"5393\",\"type\":\"Column\"},{\"attributes\":{\"text\":\"<b> Choose variable </b>\"},\"id\":\"5318\",\"type\":\"Div\"},{\"attributes\":{\"center\":[{\"id\":\"5369\"},{\"id\":\"5373\"}],\"plot_height\":300,\"plot_width\":300,\"renderers\":[{\"id\":\"5381\"},{\"id\":\"5386\"}],\"title\":{\"id\":\"5519\"},\"toolbar\":{\"id\":\"5377\"},\"toolbar_location\":\"below\",\"x_range\":{\"id\":\"5358\"},\"x_scale\":{\"id\":\"5362\"},\"y_range\":{\"id\":\"5360\"},\"y_scale\":{\"id\":\"5364\"}},\"id\":\"5357\",\"subtype\":\"Figure\",\"type\":\"Plot\"},{\"attributes\":{},\"id\":\"5340\",\"type\":\"WheelZoomTool\"},{\"attributes\":{\"axis\":{\"id\":\"5331\"},\"ticker\":null},\"id\":\"5334\",\"type\":\"Grid\"},{\"attributes\":{\"fill_color\":{\"value\":\"midnightblue\"},\"line_color\":{\"value\":\"#1f77b4\"},\"size\":{\"units\":\"screen\",\"value\":12},\"x\":{\"value\":-8235756.121250243},\"y\":{\"value\":4971018.882917135}},\"id\":\"5384\",\"type\":\"Circle\"}],\"root_ids\":[\"5395\"]},\"title\":\"Bokeh Application\",\"version\":\"2.0.1\"}};\n",
       "  var render_items = [{\"docid\":\"649a2270-4e3f-4898-be67-1bf41ea293a7\",\"root_ids\":[\"5395\"],\"roots\":{\"5395\":\"d56cda7f-3cb1-4ecf-8bbb-1a0a5796bc0f\"}}];\n",
       "  root.Bokeh.embed.embed_items_notebook(docs_json, render_items);\n",
       "\n",
       "  }\n",
       "  if (root.Bokeh !== undefined) {\n",
       "    embed_document(root);\n",
       "  } else {\n",
       "    var attempts = 0;\n",
       "    var timer = setInterval(function(root) {\n",
       "      if (root.Bokeh !== undefined) {\n",
       "        clearInterval(timer);\n",
       "        embed_document(root);\n",
       "      } else {\n",
       "        attempts++;\n",
       "        if (attempts > 100) {\n",
       "          clearInterval(timer);\n",
       "          console.log(\"Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing\");\n",
       "        }\n",
       "      }\n",
       "    }, 10, root)\n",
       "  }\n",
       "})(window);"
      ],
      "application/vnd.bokehjs_exec.v0+json": ""
     },
     "metadata": {
      "application/vnd.bokehjs_exec.v0+json": {
       "id": "5395"
      }
     },
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:bokeh.embed.util:\n",
      "You are generating standalone HTML/JS output, but trying to use real Python\n",
      "callbacks (i.e. with on_change or on_event). This combination cannot work.\n",
      "\n",
      "Only JavaScript callbacks may be used with standalone output. For more\n",
      "information on JavaScript callbacks with Bokeh, see:\n",
      "\n",
      "    https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html\n",
      "\n",
      "Alternatively, to use real Python callbacks, a Bokeh server application may\n",
      "be used. For more information on building and running Bokeh applications, see:\n",
      "\n",
      "    https://docs.bokeh.org/en/latest/docs/user_guide/server.html\n",
      "\n"
     ]
    }
   ],
   "source": [
    "\n",
    "def update1(attr, old, new):\n",
    "    plot,para,m = create_plot()\n",
    "    layout.children[1] = create_slider(plot, 2006, 2018)\n",
    "    \n",
    "\n",
    "def update2(attr, old, new):\n",
    "    plot,para,m = create_plot()\n",
    "    layout.children[2] =  para\n",
    "    layout.children[0].children[5] =  m\n",
    "    \n",
    "text_input = TextInput(value='01M140')\n",
    "text_input.on_change('value',update1,update2)\n",
    "\n",
    "\n",
    "div1 = Div(text=\"<b> Write School DBN </b>\")\n",
    "\n",
    "variables = ['Etnicities','Gender','Mean Score (only middle schools)','Graduation/Dropout (only high shools)']\n",
    "\n",
    "div2 = Div(text=\"<b> Choose variable </b>\")              \n",
    "radio_group = RadioGroup(labels=variables, active=3)\n",
    "radio_group.on_change('active',update1,update2)\n",
    "\n",
    "div3 =Div(text=\"<b> School Location </b>\") \n",
    "\n",
    "plot,para,m = create_plot()\n",
    "layout = create_slider(plot, 2006, 2018)\n",
    "\n",
    "\n",
    "#Combine all controls to get in column\n",
    "controls = column(div1,text_input,div2,radio_group,div3,m, width=300)\n",
    "\n",
    "\n",
    "#Layout\n",
    "layout = row(controls,layout,para)\n",
    "\n",
    "curdoc().add_root(layout)\n",
    "curdoc().title = \"NYC_map\"\n",
    "\n",
    "#output_file(\"details.html\")\n",
    "#save(layout)\n",
    "\n",
    "output_notebook()\n",
    "show(layout)\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
